version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - "type: dependencies"
    groups:
      ## Fastify
      # @see https://github.com/fastify
      fastify:
        patterns:
          - 'fastify*'
          - '@fastify*'
          - '*fastify*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'