'type: dependencies':
  - head-branch: ['upgrades/*', 'upgrade/*', 'dependencies/*', 'deps/*']
'type: enhancement':
  - head-branch: ['feature/*', 'feat/*', 'enhance/*', 'enhancement/*']
'type: bugfix':
  - head-branch: ['bugfix/*']
'type: hotfix':
  - head-branch: ['hotfix/*']
'type: chore':
  - head-branch: ['chore/*', 'maintenance/*', 'maintain/*']
'type: security':
  - head-branch: ['security/*']
'type: documentation':
  - head-branch: ['docs/*', 'documentation/*', 'joggr/*']
  - changed-files:
    - any-glob-to-any-file: 'docs/**'
'dep: npm':
  - all:
    - changed-files:
      - any-glob-to-any-file: 'yarn.lock'
    - head-branch: ['upgrades/*', 'upgrade/*', 'dependencies/*', 'deps/*']
