name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ':bangbang: Breaking Changes :bangbang:'
    labels:
      - 'semver: major'
  - title: '🦄 Enhancements'
    labels:
      - 'type: enhancement'
  - title: '🔥 Hotfixes'
    labels:
      - 'type: hotfix'
  - title: '🐛 Bugfixes'
    labels:
      - 'type: bugfix'
  - title: '🧰 Chore'
    labels:
      - 'type: chore'
  - title: '👮 Security'
    labels:
      - 'type: security'
  - title: '📦 Dependencies'
    labels:
      - 'type: dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-labels:
  - 'semver: skip'
version-resolver:
  major:
    labels:
      - 'semver: major'
  minor:
    labels:
      - 'semver: minor'
  patch:
    labels:
      - 'semver: patch'
  default: minor
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
