name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ':bangbang: Breaking Changes'
    labels:
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🔥 Hotfixes'
    labels:
      - 'hotfix'
  - title: '🐛 Bugfixes'
    labels:
      - 'bugfix'
  - title: '🧰 Chores'
    labels:
      - 'maintenance'
      - 'chore'
      - 'maintain'
  - title: '🛡️ Security'
    labels: 
      - 'security'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
