cacheFolder: ./.yarn/cache

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - x86
    - arm
    - arm64
    - ia32
  libc:
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.9.2.cjs
