compressionLevel: mixed
enableGlobalCache: false
cacheFolder: './.yarn/cache'
nodeLinker: node-modules
supportedArchitectures:
  cpu:
    - current
    - x64
    - x86
    - arm
    - ia32
  libc:
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
yarnPath: .yarn/releases/yarn-4.2.1.cjs
