version: '3'
services:
  postgres-db:
    image: postgres:10.3
    restart: always
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
