name: 'auto: Labeler'

on:
  - pull_request_target

concurrency:
  group: auto-labeler-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    name: Labeler
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: '⬇️ Checkout Code'
        uses: actions/checkout@v4
      - name: '🏷️ Labeler'
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yaml'
