name: 'PR Labeler'

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

concurrency:
  group: labeler-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-labeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
